{
	"_Type": "Action.Type.OpenBarcodeScanner",
	"ActionResult": {
		"_Name": "BarcodeScanner"
	},
	"OnSuccess": "/MDKFriend/Rules/BarcodeScanResult.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Reading..."
}